# This is the name of your pipeline, which will show up on GitHub
name: Spring Boot CI with Maven

# This section defines WHEN the pipeline should run
on:
  # Run it on any push to the "main" branch
  push:
    branches: [ "main" ]
  # Also run it on pull requests that target the "main" branch
  pull_request:
    branches: [ "main" ]

# This section defines the actual WORK to be done
jobs:
  build-and-test:
    # Use a standard, free virtual machine provided by GitHub
    runs-on: ubuntu-latest

    # These are the individual steps the machine will execute in order
    steps:
    # Step 1: Download your repository's code into the virtual machine
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install Java Development Kit (JDK) version 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the project and run ALL tests
    # The "mvn -B package" command compiles your code and automatically runs
    # every test in your project (Unit, BDD, and Selenium UI tests).
    - name: Build and Test with Maven
      run: mvn -B package